// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	OrderName            string   `protobuf:"bytes,2,opt,name=OrderName,proto3" json:"OrderName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *CreateOrderRequest) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

type CommonResult struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResult) Reset()         { *m = CommonResult{} }
func (m *CommonResult) String() string { return proto.CompactTextString(m) }
func (*CommonResult) ProtoMessage()    {}
func (*CommonResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{1}
}

func (m *CommonResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResult.Unmarshal(m, b)
}
func (m *CommonResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResult.Marshal(b, m, deterministic)
}
func (m *CommonResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResult.Merge(m, src)
}
func (m *CommonResult) XXX_Size() int {
	return xxx_messageInfo_CommonResult.Size(m)
}
func (m *CommonResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResult proto.InternalMessageInfo

func (m *CommonResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CommonResult) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "proto.CreateOrderRequest")
	proto.RegisterType((*CommonResult)(nil), "proto.CommonResult")
}

func init() { proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8) }

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0xd2, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x0f,
	0x97, 0x90, 0x73, 0x51, 0x6a, 0x62, 0x49, 0xaa, 0x3f, 0x48, 0x2e, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x48, 0x82, 0x8b, 0x1d, 0xcc, 0xf7, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x85, 0x64, 0xb8, 0x38, 0xc1, 0x4c, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x1c,
	0x42, 0x40, 0xc9, 0x8c, 0x8b, 0xc7, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x2f, 0x28, 0xb5, 0xb8, 0x34,
	0xa7, 0x44, 0x48, 0x88, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x15, 0x6a, 0x08, 0x98, 0x0d, 0x12, 0xcb,
	0xcc, 0x4b, 0xcb, 0x87, 0x6a, 0x06, 0xb3, 0x8d, 0x3c, 0xb8, 0x58, 0xc1, 0x86, 0x08, 0xd9, 0x73,
	0x71, 0x23, 0x39, 0x47, 0x48, 0x12, 0xe2, 0x58, 0x3d, 0x4c, 0x27, 0x4a, 0x09, 0xc3, 0xa4, 0x90,
	0xec, 0x53, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x7d,
	0x95, 0xd2, 0xf2, 0x00, 0x00, 0x00,
}
